print('*' * 1)
print('*' * 2)
print('*' * 3)
print('*' * 4)
print('*' * 5)
print()

print('*' * 5)
print('*' * 4)
print('*' * 3)
print('*' * 2)
print('*' * 1)
print()

print(' ' * 4 + '*' * 1)
print(' ' * 3 + '*' * 3)
print(' ' * 2 + '*' * 5)
print(' ' * 1 + '*' * 7)
print('*' * 9)
print()

print('*' * 9)
print(' ' * 1 + '*' * 7)
print(' ' * 2 + '*' * 5)
print(' ' * 3 + '*' * 3)
print(' ' * 4 + '*' * 1)
print()

print(' ' * 4 + '*' * 1)
print(' ' * 3 + '*' * 2)
print(' ' * 2 + '*' * 3)
print(' ' * 1 + '*' * 4)
print('*' * 5)
print()

print('*' * 5)
print(' ' * 1 + '*' * 4)
print(' ' * 2 + '*' * 3)
print(' ' * 3 + '*' * 2)
print(' ' * 4 + '*' * 1)

